image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      jekyll build
    command: |
      jekyll serve
vscode:
  extensions:
    - sissel.shopify-liquid
    - ecmel.vscode-html-css
    - yzhang.markdown-all-in-one
    - mrmlnc.vscode-scss
    - VisualStudioExptTeam.vscodeintellicode
    - christian-kohler.path-intellisense
    # - matklad.rust-analyzer