- discord:
  link: https://discord.gg/p6wqHGVMUP
- linkedin:
  company: chocolate-network
- twitter:
  user: ChocNetwork
- medium:
  user:
- litepaper:
  link: https://docs.google.com/document/d/1vFsjf2SO-spUB8JRcb6DZc8R32xMCeFnfy5b9Mu6ewE/edit?usp=sharing
- webapp:
  link: https://chocolate-demo.web.app