- discord:
  link: https://discord.gg/p6wqHGVMUP
- linkedin:
  company: chocolate-network
- twitter:
  user: ChocNetwork
- github:
  user: chocolatenetwork
- litepaper:
  link: https://docs.google.com/document/d/1vFsjf2SO-spUB8JRcb6DZc8R32xMCeFnfy5b9Mu6ewE/edit?usp=sharing
- video:
  link: https://youtu.be/pYYsq7Iy8FY